modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="weaponize"
version="${file.jarVersion}" #mandatory
displayName="Weaponize" #mandatory
authors="Lilypuree" #optional
description='''
give items attack speed and damage using datapacks
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.weaponize]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.weaponize]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
